### ISSUE TITLE
library problem

### ISSUE THREAD

**Issue by e135193** [remixer-dec/mpy-img-decoder#1]
There is a problem in the library

```
from JPEGdecoder import jpeg

def draw() :
    print('decode')

jpeg('image.jpeg', callback=draw).render(32, 32)

```

```
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "JPEGdecoder.py", line 613, in processFile
MemoryError: memory allocation failed, allocating 128 bytes
```

**Comment by remixer-dec** [comment]
Hi. You need at least 80kb of free RAM to use the library. As mentioned in README, it is only capable of rendering only small images which can fit in RAM
